CREATE TABLE IF NOT EXISTS institution
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name TEXT,
    CONSTRAINT pk_institution PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS student
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           TEXT,
    institution_id BIGINT,
    CONSTRAINT pk_student PRIMARY KEY (id)
);

ALTER TABLE student
    ADD CONSTRAINT FK_STUDENT_ON_INSTITUTION FOREIGN KEY (institution_id) REFERENCES institution (id);